##################################################
# exp_opts
##################################################
seed: 0
exp_name: 'kc_gen'
save_model: true
testing: false # only use a very small portion of the dataset for testing purposes
log_train_every_itr: 10
model_save_dir: 'checkpoints'
use_cuda: true
log_wandb: false
continue_training: false
start_epoch: 0
wandb_project: 'kc_generation_mean'
wandb_key: 'ff70920d9852a9d2e78bbd1cd2e100154d2c9c7d' #Change to your own api key
multitask: true
kc_loss: true
##################################################
# data_opts
##################################################
data_path: 'data'
test_size: 0.2 # percentage of test dataset
max_len: 20 # maximum number of submission per student
label_type: 'binary' # score division category, choose from 'binary' or 'raw'
first_ast_convertible: true # whether to use student first submission to each question
split_by: 'student'
##################################################
# model_lstm_opts
##################################################
use_lstm: true
lstm_inp_dim: 4296 # 4296: 4096+200 (200 is the astnn embedding)
# lstm_hid_dim: 11 # 11: depends on number of knowledge components created
train_lstm: true
num_layers: 1
lstm_lr: 0.0005
baseline: false
transition: false
##################################################
# model_gpt_opts
##################################################
okt_model: 'meta-llama/Meta-Llama-3-8B-Instruct' # 'meta-llama/Meta-Llama-3-8B-Instruct'
train_okt: true
##################################################
# train_generator_opts
##################################################
epochs: 1
batch_size: 2
accum_iter: 1
lr: 0.00001
trans_linear_lr: 0.0001
pred_linear_lr: 0.0001
binary_loss_fn: 'BCE'
use_scheduler: true
warmup_ratio: 0.1
alpha: 0.8
kc_loss_method: 'prod'  #could be prod, mean, or 'geo_mean'
##################################################
# LoRA configs
##################################################
lora_alpha: 256
lora_dropout: 0.05
lora_r: 128
##################################################
# evaluation configs
##################################################
nsamples: 1
k: 1
p: 0
max_new_tokens: 400
change_generation_length: false